server:
  port: 8089
spring:
  application:
    name: account
  datasource:
    username: yousef
    password: password
    url: jdbc:postgresql://localhost:5432/account
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
