spring:
  application:
    name: eureka-server
#  zipkin:
#    base-url: http://localhost:9411
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0
